### ISSUE TITLE
Question: XRoad Proxy OOM errors - how to increase memory

### ISSUE THREAD

**Issue by autero1** [nordic-institute/X-Road-Security-Server-sidecar#84]
We're seeing intermittent OutOfMemoryErrors in the sidecar (secondary). The container is deployed in Kubernetes and the Pod has 4G memory allocated - usage is around 2,5G so the Pod should have enough resources. 

How do we increase memory for the individual container processes?

**Comment by ricardas-buc** [comment]
Memory can be configured in same way as in vanilla X-Road.
An example can be found here: https://github.com/nordic-institute/X-Road/blob/beta-7.0.0/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#21-adding-command-line-arguments 

Ideally /etc/xroad should use persistent volume and configuration would reside there.

**Comment by autero1** [comment]
Thanks! I'll take a look at the X-Road documentation.
