### ISSUE TITLE
/etc/xroad/globalconf/instance-identifier is missing

### ISSUE THREAD

**Issue by UZxmRqVWQwZXfqyB** [nordic-institute/X-Road-Security-Server-sidecar#94]
After starting docker image niis/xroad-security-server-sidecar:7.2.2-slim

Failed to read instance identifier from /etc/xroad/globalconf/instance-identifier
java.io.FileNotFoundException: /etc/xroad/globalconf/instance-identifier (No such file or directory)

/etc/xroad/globalconf/ is empty

**Comment by raits** [comment]
Hello,

Are you able to access the Security Server use interface on port 4000? If so, have you initialised the Security Server? If not, it might be a harmless error since the Security Server cannot load the global configuration until the anchor is uploaded during the initialisation process.

**Comment by UZxmRqVWQwZXfqyB** [comment]
Hi, after accessing admin UI and configuring, that problem was solved. 

Just remarcs that after initializing server, backuping wont work out of the box because /var/lib/xroad/backup directory not exists.  It must be created by accessing into pod. Additionally backup fails cause /etc/xroad/lost+found is owned by root not by xroad. After changing that ownership backuping started to work.
